-- IMPORTANT: Run this SQL in your Supabase SQL Editor
-- Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/sql/new

-- Drop existing tables if they exist (clean slate)
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists cart_items cascade;
drop table if exists sessions cascade;
drop table if exists products cascade;

-- Create sessions table for guest user tracking
create table sessions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_active timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  stock integer default 0,
  image_url text,
  flavor text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create cart_items table
create table cart_items (
  id bigint generated by default as identity primary key,
  session_id uuid references sessions(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  quantity integer default 1 check (quantity > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(session_id, product_id)
);

-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  session_id uuid references sessions(id),
  total_amount numeric not null,
  status text default 'pending',
  shipping_address text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create order items table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id) not null,
  quantity integer default 1,
  price_at_purchase numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for better performance
create index idx_cart_items_session on cart_items(session_id);
create index idx_cart_items_product on cart_items(product_id);
create index idx_orders_session on orders(session_id);
create index idx_orders_status on orders(status);
create index idx_orders_created on orders(created_at desc);
create index idx_order_items_order on order_items(order_id);
create index idx_order_items_product on order_items(product_id);

-- Enable Row Level Security (RLS)
alter table sessions enable row level security;
alter table products enable row level security;
alter table cart_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- Policies for sessions
create policy "Anyone can create sessions"
  on sessions for insert
  with check ( true );

create policy "Anyone can read sessions"
  on sessions for select
  using ( true );

create policy "Anyone can update sessions"
  on sessions for update
  using ( true );

-- Policies for products
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

create policy "Anyone can insert products"
  on products for insert
  with check ( true );

create policy "Anyone can update products"
  on products for update
  using ( true );

create policy "Anyone can delete products"
  on products for delete
  using ( true );

-- Policies for cart_items
create policy "Anyone can view cart items"
  on cart_items for select
  using ( true );

create policy "Anyone can insert cart items"
  on cart_items for insert
  with check ( true );

create policy "Anyone can update cart items"
  on cart_items for update
  using ( true );

create policy "Anyone can delete cart items"
  on cart_items for delete
  using ( true );

-- Policies for orders
create policy "Anyone can view orders"
  on orders for select
  using ( true );

create policy "Anyone can insert orders"
  on orders for insert
  with check ( true );

create policy "Authenticated users can update orders"
  on orders for update
  using ( auth.role() = 'authenticated' );

-- Policies for order_items
create policy "Anyone can view order items"
  on order_items for select
  using ( true );

create policy "Anyone can insert order items"
  on order_items for insert
  with check ( true );

-- Function to update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Trigger to auto-update updated_at for cart_items
create trigger update_cart_items_updated_at
  before update on cart_items
  for each row
  execute function update_updated_at_column();

-- Function to update session last_active
create or replace function update_session_last_active()
returns trigger as $$
begin
  update sessions set last_active = timezone('utc'::text, now()) where id = new.session_id;
  return new;
end;
$$ language plpgsql;

-- Trigger to update session activity on cart changes
create trigger update_session_on_cart_change
  after insert or update on cart_items
  for each row
  execute function update_session_last_active();

-- Insert sample products
insert into products (name, description, price, stock, flavor, image_url) values
('Gedebog Original', 'Classic crispy banana stem chips.', 15000, 100, 'Original', 'https://placehold.co/400x400/png?text=Original'),
('Gedebog Balado', 'Spicy and savory balado flavor.', 16000, 80, 'Balado', 'https://placehold.co/400x400/png?text=Balado'),
('Gedebog Cheese', 'Rich cheesy flavor.', 17000, 50, 'Cheese', 'https://placehold.co/400x400/png?text=Cheese');
