-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  stock integer default 0,
  image_url text,
  flavor text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  total_amount numeric not null,
  status text default 'pending',
  shipping_address text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create order items table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id) not null,
  quantity integer default 1,
  price_at_purchase numeric not null
);

-- Enable Row Level Security (RLS)
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- Policies for products
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

create policy "Admins can insert products"
  on products for insert
  with check ( auth.role() = 'authenticated' ); -- Simplified for now, ideally check admin role

create policy "Admins can update products"
  on products for update
  using ( auth.role() = 'authenticated' );

-- Policies for orders
create policy "Users can view their own orders"
  on orders for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own orders"
  on orders for insert
  with check ( auth.uid() = user_id );

-- Insert some dummy data
insert into products (name, description, price, stock, flavor, image_url) values
('Gedebog Original', 'Classic crispy banana stem chips.', 15000, 100, 'Original', 'https://placehold.co/400x400/png?text=Original'),
('Gedebog Balado', 'Spicy and savory balado flavor.', 16000, 80, 'Balado', 'https://placehold.co/400x400/png?text=Balado'),
('Gedebog Cheese', 'Rich cheesy flavor.', 17000, 50, 'Cheese', 'https://placehold.co/400x400/png?text=Cheese');
